service: productService

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  role: ${file(../roleARN.yaml):roles.LabRole}
  environment:
    TABLE_NAME: ${self:service}-${opt:stage, 'dev'}

functions:
  getProducts:
    handler: product_lambda.get_products
    events:
      - http:
          path: /products
          method: get
          cors: true

  createProduct:
    handler: product_lambda.create_product
    events:
      - http:
          path: /products
          method: post
          cors: true

  manageProduct:
    handler: product_lambda.manage_product
    events:
      - http:
          path: /products/{product_id}
          method: get
          cors: true
      - http:
          path: /products/{product_id}
          method: put
          cors: true
      - http:
          path: /products/{product_id}
          method: delete
          cors: true

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
