org: fabriciobautista
service: api-reportes

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::359604420564:role/LabRole 
  environment:
    TABLE_NAME: ${self:service}-${self:provider.stage}-reportes

functions:
  createSalesReport:
    handler: handlers/reportes.createSalesReport
    events:
      - http:
          path: /reports/sales
          method: post
          cors: true
          authorizer: aws_iam

  getSalesReport:
    handler: handlers/reportes.getSalesReport
    events:
      - http:
          path: /reports/sales/{report_id}
          method: get
          cors: true
          authorizer: aws_iam

  listSalesReports:
    handler: handlers/reportes.listSalesReports
    events:
      - http:
          path: /reports/sales
          method: get
          cors: true
          authorizer: aws_iam

resources:
  Resources:
    ReportesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: report_id
            AttributeType: S
          - AttributeName: report_type
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: report_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ReportTypeIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: report_type
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        LocalSecondaryIndexes:
          - IndexName: ReportDateIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

plugins:
  - serverless-offline
